name: 'dbt-snowflake'
version: '1.0'
config-version: 2

profile: 'dbt-snowflake'

model-paths:
  - models/raw/tpch
  - models/staging/tpch
  - models/intermediate/tpch
  - models/marts/core
  - models/tests

models:
  dbt-snowflake:
    raw:
      +schema: raw
    staging:
      +schema: stg  # or leave this line out to use default
    intermediate:
      +schema: int  # or leave this line out to use default
    marts:
      +schema: core