name: 'snowflake_analytics'
version: '1.0'
config-version: 2

profile: 'snowflake_analytics'

model-paths:
  - models

models:
  snowflake_analytics:
    sfa:
      raw:
        +schema: raw
      staging:
        +schema: stg
      intermediate:
        +schema: int
      marts:
        +schema: core
