version: "3.8"

services:
  dbt:
    image: ghcr.io/dbt-labs/dbt-snowflake:1.6.5
    container_name: snowflake_analytics_dbt
    environment:
      - SNOWFLAKE_ACCOUNT=${SNOWFLAKE_ACCOUNT}
      - SNOWFLAKE_DEV_ACCOUNT=${SNOWFLAKE_DEV_ACCOUNT}
      - SNOWFLAKE_USER=${SNOWFLAKE_USER}
      - SNOWFLAKE_DEV_USER=${SNOWFLAKE_DEV_USER}
      - SNOWFLAKE_PASSWORD=${SNOWFLAKE_PASSWORD}
      - SNOWFLAKE_DEV_PASSWORD=${SNOWFLAKE_DEV_PASSWORD}
      - SNOWFLAKE_ROLE=${SNOWFLAKE_ROLE}
      - SNOWFLAKE_DEV_ROLE=${SNOWFLAKE_DEV_ROLE}
    volumes:
      - ./:/usr/app
      - ./profiles:/root/.dbt
    working_dir: /usr/app
    entrypoint: ["tail", "-f", "/dev/null"]
