snowflake_analytics:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: wf35605.europe-west3.gcp
      user: anoopr
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: ACCOUNTADMIN
      database: DBT_ANALYTICS
      warehouse: COMPUTE_WH
      schema: CORE
      threads: 4
      client_session_keep_alive: False

test_profile:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: iv50318.europe-west3.gcp
      user: neodeja
      password: "{{ env_var('SNOWFLAKE_DEV_PASSWORD') }}"
      role: ACCOUNTADMIN
      database: TEST_DB
      warehouse: COMPUTE_WH
      schema: TEST_SCHEMA
      threads: 4
      client_session_keep_alive: False